version: "2"
services:
  elasticsearch:
      image: elasticsearch:latest
      command: elasticsearch -Des.network.bindHost=0.0.0.0
      restart: unless-stopped
      volumes:
        - "./esdata:/usr/share/elasticsearch/data"
  web:
      build: .
      ports:
        - "3000:3000"
      links:
        - elasticsearch
      env_file: ./.env
      entrypoint: dockerize -timeout 60s -wait tcp://elasticsearch:9200 -wait tcp://elasticsearch:9300 npm start
      restart: unless-stopped
